# Site Settings
paginate:            5
github:
  url: https://www.shiphp.com

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /blog/:year/:title
plugins:             [jekyll-paginate, jekyll-sitemap]
