# Site Settings
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /blog/:year/:title
plugins:             [jekyll-paginate, jekyll-sitemap]
