# Site Settings
paginate:            10
github:
  url: https://www.shiphp.com

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /blog/:title
paginate_path:       /page/:num/
plugins:             [jekyll-paginate, jekyll-sitemap]
